server:
  port: 9004

spring:
  application:
    name: token-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9941