server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/**

        - id: email-service
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path=/api/**

        - id: token-service
          uri: lb://TOKEN-SERVICE
          predicates:
            - Path=/api/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9941
#      routes:
# todo need to find how to configure routes for gateway for many endpoints and services
jwt:
  secret: 4jE4XcimwrEF9PUiOGaasXROjlw9zpkj5Hr59gojyiE6SMcxDBf9sJu/sCX/eazVrd+TyfYB/e8mz0NmgzuMNYmeb/Cw4aI1wOVgihSrVxT9erUXQXaGD8chY4wdWI9yaZOQKOdHcq8HTLYde3Xum34hgIMG3UJfHIfUNfL0a8Z6YiZGnuEnZrCsmMPTufN0o+pWQk5e7NI7fAgveTBvcV04oLJKK5sjky8a3N9rVPX2XZ6UOsG2n7Cvn/940dpy+DqRPBYCfagUyKNmakjAV2Desn7FkZ7dlGgsZGaWvXm3dhQ1l9TSdZTyx6QlLyaLB95pCDojfwaCYwKTEmj6
  expiration: 86400000
tokenValidityTimeInMinutes: 30