server:
  port: 9002

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

spring:
  application:
    name: user-service
  profiles:
    active: default

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
    endpoint:
      health:
        probes:
          enabled: true
        show-details: always
        show-components: always
    metrics:
      tags:
        application: ${spring.application.name}
      distribution:
        percentiles-histogram:
          all: true
          http.server.requests: true
    tracing:
      sampling:
        probability: 1.0
    prometheus:
      metrics:
        export:
          step: 10s
    info:
      env:
        enabled: true
      java:
        enabled: true
      os:
        enabled: true