server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: discovery-service
  profiles:
    active: default

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9941