server:
  port: 9297

spring:
  application:
    name: config-service
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chrzanekk/demo-config-server.git
          clone-on-start: true